import type { CitySummary, DeptSummary } from "@/types";

export const SITE_CONFIG = {
  name: "Épaviste IDF",
  /** Nom affiché dans les données structurées Schema.org */
  schemaBrandName: "Épaviste IDF Pro",
  phone: "07 56 84 25 87",
  phoneHref: "tel:+33756842587",
  email: "contact@epaviste-idf-pro.fr",
  url: "https://www.epaviste-idf-pro.fr",
  address: "Île-de-France, France",
  openingHours: "Lun-Dim 7h-22h",
  rating: 4.9,
  reviewCount: 247,
  vehiclesCount: 2350,
  tagline:
    "Épaviste agréé • Enlèvement gratuit 24h/24 • Rachat au meilleur prix",
  description:
    "Épaviste agréé en Île-de-France. Enlèvement épave gratuit sous 24h, rachat épave au meilleur prix, certificat de destruction VHU officiel. Intervention dans les 8 départements IDF.",
} as const;

function parisDistricts(): string[] {
  const ord = (n: number) => (n === 1 ? "1er" : `${n}e`);
  return Array.from({ length: 20 }, (_, i) => `Paris ${ord(i + 1)}`);
}

export const DEPARTMENTS: DeptSummary[] = [
  {
    name: "Paris",
    code: "75",
    slug: "paris-75",
    cities: parisDistricts(),
  },
  {
    name: "Seine-et-Marne",
    code: "77",
    slug: "seine-et-marne-77",
    cities: [
      "Meaux",
      "Chelles",
      "Melun",
      "Fontainebleau",
      "Provins",
      "Torcy",
      "Pontault-Combault",
      "Roissy-en-Brie",
      "Combs-la-Ville",
      "Ozoir-la-Ferrière",
      "Lagny-sur-Marne",
      "Noisiel",
      "Dammarie-les-Lys",
      "Montereau-Fault-Yonne",
      "Serris",
      "Bussy-Saint-Georges",
      "Savigny-le-Temple",
      "Coulommiers",
      "Nemours",
      "Claye-Souilly",
    ],
  },
  {
    name: "Yvelines",
    code: "78",
    slug: "yvelines-78",
    cities: [
      "Versailles",
      "Saint-Germain-en-Laye",
      "Sartrouville",
      "Poissy",
      "Conflans-Sainte-Honorine",
      "Houilles",
      "Les Mureaux",
      "Plaisir",
      "Trappes",
      "Rambouillet",
      "Mantes-la-Jolie",
      "Guyancourt",
      "Vélizy-Villacoublay",
      "Chatou",
      "Le Pecq",
      "Marly-le-Roi",
      "Carrières-sous-Poissy",
      "Le Chesnay-Rocquencourt",
      "Achères",
      "Montigny-le-Bretonneux",
    ],
  },
  {
    name: "Essonne",
    code: "91",
    slug: "essonne-91",
    cities: [
      "Évry-Courcouronnes",
      "Corbeil-Essonnes",
      "Massy",
      "Savigny-sur-Orge",
      "Sainte-Geneviève-des-Bois",
      "Athis-Mons",
      "Viry-Châtillon",
      "Draveil",
      "Palaiseau",
      "Yerres",
      "Longjumeau",
      "Juvisy-sur-Orge",
      "Ris-Orangis",
      "Brétigny-sur-Orge",
      "Étampes",
      "Arpajon",
      "Gif-sur-Yvette",
      "Les Ulis",
      "Morangis",
      "Orsay",
    ],
  },
  {
    name: "Hauts-de-Seine",
    code: "92",
    slug: "hauts-de-seine-92",
    cities: [
      "Boulogne-Billancourt",
      "Nanterre",
      "Courbevoie",
      "Colombes",
      "Asnières-sur-Seine",
      "Rueil-Malmaison",
      "Levallois-Perret",
      "Issy-les-Moulineaux",
      "Antony",
      "Clamart",
      "Neuilly-sur-Seine",
      "Clichy",
      "Puteaux",
      "Suresnes",
      "Vanves",
      "Meudon",
      "Montrouge",
      "Bagneux",
      "Saint-Cloud",
      "Sceaux",
    ],
  },
  {
    name: "Seine-Saint-Denis",
    code: "93",
    slug: "seine-saint-denis-93",
    cities: [
      "Saint-Denis",
      "Montreuil",
      "Aubervilliers",
      "Drancy",
      "Noisy-le-Grand",
      "Pantin",
      "Bondy",
      "Épinay-sur-Seine",
      "Le Blanc-Mesnil",
      "Sevran",
      "Aulnay-sous-Bois",
      "Bobigny",
      "Villepinte",
      "Tremblay-en-France",
      "Rosny-sous-Bois",
      "Bagnolet",
      "Les Lilas",
      "Noisy-le-Sec",
      "La Courneuve",
      "Pierrefitte-sur-Seine",
    ],
  },
  {
    name: "Val-de-Marne",
    code: "94",
    slug: "val-de-marne-94",
    cities: [
      "Créteil",
      "Vitry-sur-Seine",
      "Saint-Maur-des-Fossés",
      "Champigny-sur-Marne",
      "Ivry-sur-Seine",
      "Villejuif",
      "Le Perreux-sur-Marne",
      "Fontenay-sous-Bois",
      "Nogent-sur-Marne",
      "Alfortville",
      "Maisons-Alfort",
      "Charenton-le-Pont",
      "Joinville-le-Pont",
      "Vincennes",
      "L'Haÿ-les-Roses",
      "Choisy-le-Roi",
      "Thiais",
      "Orly",
      "Villeneuve-Saint-Georges",
      "Chevilly-Larue",
    ],
  },
  {
    name: "Val-d'Oise",
    code: "95",
    slug: "val-d-oise-95",
    cities: [
      "Argenteuil",
      "Cergy",
      "Sarcelles",
      "Garges-lès-Gonesse",
      "Franconville",
      "Ermont",
      "Bezons",
      "Herblay-sur-Seine",
      "Taverny",
      "Goussainville",
      "Pontoise",
      "Saint-Ouen-l'Aumône",
      "Eaubonne",
      "Montmorency",
      "Deuil-la-Barre",
      "Domont",
      "Sannois",
      "Soisy-sous-Montmorency",
      "Villiers-le-Bel",
      "Cormeilles-en-Parisis",
    ],
  },
];

export const CITIES: CitySummary[] = [
  {
    name: "Paris",
    slug: "paris",
    dept: "75",
    population: 2_148_000,
    description:
      "Capitale dense et multipolaire, Paris concentre des épaves en stationnement, cours et garages : nos équipes interviennent rapidement sur les arrondissements centraux et périphériques avec enlèvement gratuit et démarches VHU conformes.",
    neighborhoods: [
      "Marais",
      "Montmartre",
      "Bastille",
      "Quartier Latin",
      "Champs-Élysées",
      "Belleville",
      "Batignolles",
      "Alésia",
    ],
  },
  {
    name: "Boulogne-Billancourt",
    slug: "boulogne-billancourt",
    dept: "92",
    population: 117_000,
    description:
      "Ville du périphérique ouest très circulée, entre Paris et la boucle de la Seine : idéal pour une enlèvement express près des axes A13 et Pont de Sèvres, avec stationnement parfois contraint.",
    neighborhoods: [
      "Silvia Monfort",
      "Point du Jour",
      "Billancourt",
      "République",
      "Marcel Sembat",
    ],
  },
  {
    name: "Saint-Denis",
    slug: "saint-denis",
    dept: "93",
    population: 112_000,
    description:
      "Pôle historique et grand équipement du nord de l’agglomération : nous desservons le centre-bourg, la Plaine Saint-Denis et les abords du stade pour les véhicules hors d’usage ou accidentés.",
    neighborhoods: [
      "Centre historique",
      "Pleyel",
      "Franc-Moisin",
      "La Plaine",
      "Basilique",
    ],
  },
  {
    name: "Argenteuil",
    slug: "argenteuil",
    dept: "95",
    population: 110_000,
    description:
      "Première commune du Val-d’Oise par la population, fortement urbanisée le long de la Seine et de l’A15 : interventions fréquentes pour épaves en impasse ou véhicules sans carte grise.",
    neighborhoods: [
      "Val d’Argent",
      "Châtelets",
      "Hauts d’Argenteuil",
      "Orgemont",
      "Petit Nanterre",
    ],
  },
  {
    name: "Montreuil",
    slug: "montreuil",
    dept: "93",
    population: 111_000,
    description:
      "Ville dense à la limite de Paris, avec de nombreuses cours et parkings souterrains : nous planifions l’accès camion plateau selon vos contraintes de gabarit et horaires.",
    neighborhoods: [
      "République",
      "Bas Montreuil",
      "La Noue",
      "Solidarité Carnot",
      "Vincennes limite",
    ],
  },
  {
    name: "Versailles",
    slug: "versailles",
    dept: "78",
    population: 85_000,
    description:
      "Centre des Yvelines au patrimoine classé : nos enlèvements respectent les règles de circulation locales et les zones à stationnement réglementé, avec créneaux précis.",
    neighborhoods: [
      "Notre-Dame",
      "Saint-Louis",
      "Montreuil",
      "Porchefontaine",
      "Chantiers",
    ],
  },
  {
    name: "Nanterre",
    slug: "nanterre",
    dept: "92",
    population: 96_000,
    description:
      "Préfecture des Hauts-de-Seine et ville universitaire : forte demande pour rachat d’épave et certificats de destruction après sinistre ou panne mécanique lourde.",
    neighborhoods: [
      "Centre-ville",
      "Université",
      "Petit Nanterre",
      "Joliot-Curie",
      "Pablo Picasso",
    ],
  },
  {
    name: "Vitry-sur-Seine",
    slug: "vitry-sur-seine",
    dept: "94",
    population: 95_000,
    description:
      "Commune du Val-de-Marne en bord de Seine avec zones industrielles et résidentielles : nous acheminons les VHU vers le parcours agréé avec enlèvement gratuit côté particulier.",
    neighborhoods: [
      "Plateau",
      "Port à l’Anglais",
      "Mairie",
      "Stalingrad",
      "Muscadiers",
    ],
  },
  {
    name: "Créteil",
    slug: "creteil",
    dept: "94",
    population: 92_000,
    description:
      "Préfecture du Val-de-Marne et ville lacustre : interventions sur îlots pavillonnaires et grands ensembles, avec optimisation des itinéraires par les ponts et rocades.",
    neighborhoods: [
      "Préfecture",
      "Mont-Mesly",
      "Pompadour",
      "Échat",
      "Bords de Marne",
    ],
  },
  {
    name: "Asnières-sur-Seine",
    slug: "asnieres-sur-seine",
    dept: "92",
    population: 85_000,
    description:
      "Ville riveraine entre Paris et la Défense : beaucoup de véhicules de fin de vie en stationnement longue durée ; nous assurons l’enlèvement sous 24 à 48 h selon planning.",
    neighborhoods: [
      "Bords de Seine",
      "Bécon",
      "Les Bruyères",
      "Courcelles",
      "Gabriel Péri",
    ],
  },
  {
    name: "Chelles",
    slug: "chelles",
    dept: "77",
    population: 55_000,
    description:
      "Chelles est un pôle majeur de Seine-et-Marne ouest : nous retirons rapidement les épaves en parking résidentiel, voie privée et zones d’activité proches des axes A104 et A4.",
    neighborhoods: ["Centre-ville", "Chantereine", "Mont-Chalats", "Foch", "Gare"],
  },
  {
    name: "Melun",
    slug: "melun",
    dept: "77",
    population: 42_000,
    description:
      "À Melun et son agglomération, nous gérons enlèvement d’épave gratuit et rachat avec créneaux adaptés aux rues denses du centre et aux quartiers périphériques.",
    neighborhoods: ["Centre", "Saint-Liesne", "Almont", "Lemot", "Schuman"],
  },
  {
    name: "Meaux",
    slug: "meaux",
    dept: "77",
    population: 56_000,
    description:
      "Meaux concentre un trafic soutenu en entrée de ville : nos équipes interviennent sous 24–48 h pour retirer les véhicules hors d’usage en zone résidentielle ou commerciale.",
    neighborhoods: ["Centre historique", "Beauval", "Foch", "Dunant", "Marché"],
  },
  {
    name: "Mantes-la-Jolie",
    slug: "mantes-la-jolie",
    dept: "78",
    population: 44_000,
    description:
      "Mantes-la-Jolie et la vallée de Seine nécessitent des interventions structurées : enlèvement rapide, accès validé à l’avance et certificat VHU remis selon le parcours.",
    neighborhoods: ["Centre-ville", "Val Fourré", "Gassicourt", "Martraits", "Mantes-Station"],
  },
  {
    name: "Saint-Germain-en-Laye",
    slug: "saint-germain-en-laye",
    dept: "78",
    population: 45_000,
    description:
      "Dans les secteurs résidentiels de Saint-Germain-en-Laye, nous assurons un enlèvement discret et ponctuel des épaves avec respect des accès privés et du voisinage.",
    neighborhoods: ["Centre", "Bel-Air", "Pereire", "Schnapper", "Hôpital"],
  },
  {
    name: "Poissy",
    slug: "poissy",
    dept: "78",
    population: 40_000,
    description:
      "Poissy combine quartiers résidentiels et zones d’activité : enlèvement épave gratuit et rachat avec délais courts et accompagnement administratif complet.",
    neighborhoods: ["Centre-ville", "Beauregard", "Noailles", "La Coudraie", "Saint-Exupéry"],
  },
  {
    name: "Corbeil-Essonnes",
    slug: "corbeil-essonnes",
    dept: "91",
    population: 53_000,
    description:
      "À Corbeil-Essonnes, nous traitons les épaves de particuliers et professionnels avec intervention rapide sur les quartiers centraux et axes sud franciliens.",
    neighborhoods: ["Centre", "Tarterêts", "Montconseil", "Pressoir Prompt", "Bas Coudray"],
  },
  {
    name: "Évry-Courcouronnes",
    slug: "evry-courcouronnes",
    dept: "91",
    population: 67_000,
    description:
      "Évry-Courcouronnes est un pôle majeur de l’Essonne : enlèvement VHU sous 24–48 h, rachat selon état, et certificat destruction pour clôturer le dossier.",
    neighborhoods: ["Pyramides", "Aguado", "Canal", "Bois Sauvage", "Mairie"],
  },
  {
    name: "Palaiseau",
    slug: "palaiseau",
    dept: "91",
    population: 37_000,
    description:
      "Entre zones pavillonnaires et secteur du plateau, nous intervenons à Palaiseau pour enlèvement épave et rachat avec accès validés en amont.",
    neighborhoods: ["Centre", "Lozère", "Pileu", "Camille Claudel", "Polytechnique"],
  },
  {
    name: "Levallois-Perret",
    slug: "levallois-perret",
    dept: "92",
    population: 68_000,
    description:
      "Levallois-Perret impose une logistique fine en environnement dense : nos équipes enlèvent les épaves rapidement avec coordination parking et copropriété.",
    neighborhoods: ["Front de Seine", "Collange", "Eiffel", "Gare", "Villiers"],
  },
  {
    name: "Neuilly-sur-Seine",
    slug: "neuilly-sur-seine",
    dept: "92",
    population: 60_000,
    description:
      "À Neuilly-sur-Seine, nous intervenons avec discrétion et précision pour les enlèvements VHU en résidence, voie privée ou stationnement contraint.",
    neighborhoods: ["Sablons", "Bagatelle", "Saint-James", "Madrid", "Pont de Neuilly"],
  },
  {
    name: "Colombes",
    slug: "colombes",
    dept: "92",
    population: 89_000,
    description:
      "Colombes présente une forte demande d’enlèvement d’épaves : intervention locale rapide, rachat possible et remise des documents nécessaires.",
    neighborhoods: ["Centre", "Petit-Colombes", "Europe", "Gare du Stade", "Agent Sarre"],
  },
  {
    name: "Aubervilliers",
    slug: "aubervilliers",
    dept: "93",
    population: 91_000,
    description:
      "Aubervilliers nécessite des créneaux réactifs et adaptés au trafic : nous retirons les véhicules hors d’usage avec prise en charge réglementaire.",
    neighborhoods: ["Centre", "Landy", "Fort d'Aubervilliers", "Quatre Chemins", "Villette"],
  },
  {
    name: "Pantin",
    slug: "pantin",
    dept: "93",
    population: 61_000,
    description:
      "À Pantin, nos équipes enlèvent les épaves en parking et en voirie autorisée, avec coordination fine autour des canaux et axes très fréquentés.",
    neighborhoods: ["Église", "Quatre-Chemins", "Hoche", "Ourcq", "Mairie"],
  },
  {
    name: "Aulnay-sous-Bois",
    slug: "aulnay-sous-bois",
    dept: "93",
    population: 88_000,
    description:
      "Aulnay-sous-Bois combine zones pavillonnaires et grands axes : enlèvement épave gratuit et rachat avec réponse rapide 7j/7.",
    neighborhoods: ["Rose-des-Vents", "Vieux-Pays", "Sud", "Savigny", "Pont de l'Union"],
  },
  {
    name: "Ivry-sur-Seine",
    slug: "ivry-sur-seine",
    dept: "94",
    population: 65_000,
    description:
      "À Ivry-sur-Seine, nous assurons enlèvement VHU et rachat sur les secteurs résidentiels et industriels proches de Paris et du périphérique.",
    neighborhoods: ["Petit-Ivry", "Ivry-Port", "Centre-ville", "Plateau", "Confluences"],
  },
  {
    name: "Villejuif",
    slug: "villejuif",
    dept: "94",
    population: 58_000,
    description:
      "Villejuif bénéficie de nos équipes locales pour retirer rapidement les épaves en sous-sol, résidence ou voirie autorisée, avec documents conformes.",
    neighborhoods: ["Centre", "Guipons", "Lion d'Or", "Paul Vaillant-Couturier", "Hautes-Bruyères"],
  },
  {
    name: "Champigny-sur-Marne",
    slug: "champigny-sur-marne",
    dept: "94",
    population: 77_000,
    description:
      "Sur Champigny-sur-Marne, nous intervenons sur les quartiers pavillonnaires et denses avec enlèvement rapide, rachat selon état et certificat de destruction.",
    neighborhoods: ["Plant", "Polangis", "Le Maroc", "Coeuilly", "Bois l'Abbé"],
  },
  {
    name: "Cergy",
    slug: "cergy",
    dept: "95",
    population: 66_000,
    description:
      "Cergy est un pôle stratégique du Val-d’Oise : enlèvement épave gratuit, rachat et accompagnement administratif sur tous les quartiers.",
    neighborhoods: ["Cergy-Préfecture", "Cergy-le-Haut", "Saint-Christophe", "Port", "Grand Centre"],
  },
  {
    name: "Sarcelles",
    slug: "sarcelles",
    dept: "95",
    population: 59_000,
    description:
      "À Sarcelles, nous enlevons les véhicules hors d’usage en intervention rapide avec organisation adaptée aux accès d’immeubles et axes urbains.",
    neighborhoods: ["Flanades", "Village", "Rosiers", "Lochères", "Chardonnerettes"],
  },
  {
    name: "Torcy",
    slug: "torcy",
    dept: "77",
    population: 24_000,
    description: "Intervention épaviste rapide à Torcy et zones voisines, enlèvement gratuit et rachat selon état.",
    neighborhoods: ["Centre", "Arche Guédon", "Mail", "Lac", "Gare"],
  },
  {
    name: "Noisiel",
    slug: "noisiel",
    dept: "77",
    population: 17_000,
    description: "À Noisiel, enlèvement d’épave sous 24–48h avec gestion des accès en résidence et zones mixtes.",
    neighborhoods: ["Luzard", "Ferme du Buisson", "Centre", "Parc", "Rive"],
  },
  {
    name: "Lagny-sur-Marne",
    slug: "lagny-sur-marne",
    dept: "77",
    population: 22_000,
    description: "Service épaviste local sur Lagny-sur-Marne avec prise en charge VHU complète et devis immédiat.",
    neighborhoods: ["Centre", "Saint-Laurent", "Tournelles", "Orme Bossu", "Bords de Marne"],
  },
  {
    name: "Pontault-Combault",
    slug: "pontault-combault",
    dept: "77",
    population: 38_000,
    description: "Enlèvement épave et rachat à Pontault-Combault, intervention rapide 7j/7.",
    neighborhoods: ["Centre", "Boullereaux", "Mairie", "Pavillonnaire", "Gare"],
  },
  {
    name: "Sartrouville",
    slug: "sartrouville",
    dept: "78",
    population: 53_000,
    description: "Sartrouville : enlèvement gratuit, rachat d’épave et accompagnement administratif.",
    neighborhoods: ["Centre", "Les Indes", "Dix Arpents", "Croix Blanche", "La Plaine"],
  },
  {
    name: "Conflans-Sainte-Honorine",
    slug: "conflans-sainte-honorine",
    dept: "78",
    population: 36_000,
    description: "Interventions épaviste à Conflans-Sainte-Honorine avec créneaux rapides.",
    neighborhoods: ["Centre", "Chennevières", "Fin d’Oise", "Romagné", "Montaigne"],
  },
  {
    name: "Les Mureaux",
    slug: "les-mureaux",
    dept: "78",
    population: 33_000,
    description: "Service VHU aux Mureaux : enlèvement, rachat et certificat de destruction.",
    neighborhoods: ["Centre", "Bécheville", "Vigne Blanche", "Sablons", "Gare"],
  },
  {
    name: "Trappes",
    slug: "trappes",
    dept: "78",
    population: 33_000,
    description: "Épaviste Trappes : prise en charge rapide de véhicules hors d’usage.",
    neighborhoods: ["Centre", "Merisiers", "Aérostat", "Plaine de Neauphle", "Boissière"],
  },
  {
    name: "Massy",
    slug: "massy",
    dept: "91",
    population: 52_000,
    description: "Massy : enlèvement épave sous 24–48h, rachat selon valorisation et dossier clair.",
    neighborhoods: ["Atlantis", "Opéra", "Villaine", "Vilmorin", "Centre"],
  },
  {
    name: "Longjumeau",
    slug: "longjumeau",
    dept: "91",
    population: 21_000,
    description: "Intervention épaviste à Longjumeau avec service agréé et accompagnement VHU.",
    neighborhoods: ["Centre", "Balizy", "Gravigny", "Poitou", "Yvette"],
  },
  {
    name: "Juvisy-sur-Orge",
    slug: "juvisy-sur-orge",
    dept: "91",
    population: 18_000,
    description: "Juvisy-sur-Orge : enlèvement d’épave rapide sur zones résidentielles et axes passants.",
    neighborhoods: ["Centre", "Seine", "Plateau", "Gare", "Concorde"],
  },
  {
    name: "Ris-Orangis",
    slug: "ris-orangis",
    dept: "91",
    population: 30_000,
    description: "Service épaviste Ris-Orangis : rachat possible, enlèvement gratuit selon cas.",
    neighborhoods: ["Centre", "Moulin à Vent", "Trousseau", "Aunettes", "Plateau"],
  },
  {
    name: "Issy-les-Moulineaux",
    slug: "issy-les-moulineaux",
    dept: "92",
    population: 69_000,
    description: "Issy-les-Moulineaux : interventions rapides en environnement dense et parkings complexes.",
    neighborhoods: ["Mairie", "Corentin Celton", "Les Varennes", "Fort d’Issy", "Bords de Seine"],
  },
  {
    name: "Clichy",
    slug: "clichy",
    dept: "92",
    population: 64_000,
    description: "Clichy : enlèvement VHU et rachat d’épave avec créneaux optimisés.",
    neighborhoods: ["Centre", "Bac d’Asnières", "Entrée de Ville", "Berges", "Victor Hugo"],
  },
  {
    name: "Puteaux",
    slug: "puteaux",
    dept: "92",
    population: 45_000,
    description: "Puteaux et secteur La Défense : prise en charge épave rapide et fiable.",
    neighborhoods: ["Centre", "La Défense", "Bellini", "Pressensé", "Berges"],
  },
  {
    name: "Rueil-Malmaison",
    slug: "rueil-malmaison",
    dept: "92",
    population: 79_000,
    description: "Rueil-Malmaison : enlèvement épave gratuit et rachat avec suivi administratif.",
    neighborhoods: ["Centre", "Buzenval", "Plateau", "Bords de Seine", "Mont-Valérien"],
  },
  {
    name: "Bobigny",
    slug: "bobigny",
    dept: "93",
    population: 55_000,
    description: "Bobigny : épaviste local, intervention rapide et documents VHU conformes.",
    neighborhoods: ["Centre", "Édouard Vaillant", "Paul Éluard", "Karl Marx", "Pont de Pierre"],
  },
  {
    name: "Drancy",
    slug: "drancy",
    dept: "93",
    population: 73_000,
    description: "Drancy : enlèvement d’épaves sous 24–48 h et rachat selon état du véhicule.",
    neighborhoods: ["Centre", "Paris Campagne", "Avenir", "Petit Drancy", "Village Parisien"],
  },
  {
    name: "Rosny-sous-Bois",
    slug: "rosny-sous-bois",
    dept: "93",
    population: 46_000,
    description: "Rosny-sous-Bois : enlèvement VHU rapide sur tous quartiers et zones commerçantes.",
    neighborhoods: ["Centre", "Bois Perrier", "Justice", "Boutours", "Rosny 2"],
  },
  {
    name: "Noisy-le-Sec",
    slug: "noisy-le-sec",
    dept: "93",
    population: 45_000,
    description: "Noisy-le-Sec : service épaviste agréé avec intervention rapide et devis gratuit.",
    neighborhoods: ["Centre", "Merlan", "Londeau", "Petit Noisy", "Gare"],
  },
  {
    name: "Maisons-Alfort",
    slug: "maisons-alfort",
    dept: "94",
    population: 58_000,
    description: "Maisons-Alfort : enlèvement d’épave et rachat avec process clair et rapide.",
    neighborhoods: ["Centre", "Charentonneau", "École Vétérinaire", "Alfort", "Berges"],
  },
  {
    name: "Alfortville",
    slug: "alfortville",
    dept: "94",
    population: 45_000,
    description: "Alfortville : interventions épaviste locales, y compris en accès parking contraint.",
    neighborhoods: ["Nord", "Sud", "Confluent", "Mairie", "Vert-de-Maisons"],
  },
  {
    name: "Vincennes",
    slug: "vincennes",
    dept: "94",
    population: 50_000,
    description: "Vincennes : enlèvement épave rapide avec adaptation aux secteurs résidentiels.",
    neighborhoods: ["Centre", "Diderot", "Bérault", "Château", "Saint-Louis"],
  },
  {
    name: "Nogent-sur-Marne",
    slug: "nogent-sur-marne",
    dept: "94",
    population: 33_000,
    description: "Nogent-sur-Marne : service VHU agréé, rachat possible et certificat de destruction.",
    neighborhoods: ["Centre", "Bords de Marne", "Port", "Beauté", "Plaisance"],
  },
  {
    name: "Ermont",
    slug: "ermont",
    dept: "95",
    population: 29_000,
    description: "Ermont : enlèvement épave gratuit et rachat selon la valorisation.",
    neighborhoods: ["Centre", "Cernay", "Gare", "Espérances", "Chênes"],
  },
  {
    name: "Gonesse",
    slug: "gonesse",
    dept: "95",
    population: 27_000,
    description: "Gonesse : interventions rapides sur secteurs résidentiels et zones d’activité.",
    neighborhoods: ["Centre", "Grande Vallée", "Mairie", "Pont", "Parc"],
  },
  {
    name: "Pontoise",
    slug: "pontoise",
    dept: "95",
    population: 31_000,
    description: "Pontoise : enlèvement d’épaves avec process VHU conforme et réactif.",
    neighborhoods: ["Centre", "Notre-Dame", "L'Hermitage", "Louvrais", "Bossut"],
  },
  {
    name: "Garges-lès-Gonesse",
    slug: "garges-les-gonesse",
    dept: "95",
    population: 43_000,
    description: "Garges-lès-Gonesse : service épaviste local, devis immédiat et intervention rapide.",
    neighborhoods: ["Centre", "Dame Blanche", "La Muette", "Les Doucettes", "Cottages"],
  },
  {
    name: "Fontainebleau",
    slug: "fontainebleau",
    dept: "77",
    population: 16_000,
    description: "Fontainebleau : enlèvement épave rapide avec prise en charge VHU conforme.",
    neighborhoods: ["Centre", "Sous-Préfecture", "Hôpital", "Forêt", "Plaine de la Chambre"],
  },
  {
    name: "Provins",
    slug: "provins",
    dept: "77",
    population: 12_000,
    description: "Provins : intervention épaviste locale, rachat possible et devis immédiat.",
    neighborhoods: ["Ville Haute", "Ville Basse", "Gare", "Sainte-Croix", "Saint-Brice"],
  },
  {
    name: "Dammarie-les-Lys",
    slug: "dammarie-les-lys",
    dept: "77",
    population: 23_000,
    description: "Dammarie-les-Lys : enlèvement VHU gratuit selon cas, service 7j/7.",
    neighborhoods: ["Centre", "Plaine du Lys", "Abbaye", "Gare", "Résidentiel"],
  },
  {
    name: "Bussy-Saint-Georges",
    slug: "bussy-saint-georges",
    dept: "77",
    population: 27_000,
    description: "Bussy-Saint-Georges : épaviste local avec intervention rapide en résidence.",
    neighborhoods: ["Centre", "Parc", "Gare", "Sycomore", "Genitoy"],
  },
  {
    name: "Guyancourt",
    slug: "guyancourt",
    dept: "78",
    population: 29_000,
    description: "Guyancourt : enlèvement épave et rachat avec créneaux optimisés.",
    neighborhoods: ["Villaroy", "Pont du Routoir", "Europe", "Saules", "Centre"],
  },
  {
    name: "Vélizy-Villacoublay",
    slug: "velizy-villacoublay",
    dept: "78",
    population: 23_000,
    description: "Vélizy-Villacoublay : service VHU rapide sur zones résidentielles et d'activité.",
    neighborhoods: ["Vélizy I", "Vélizy II", "Louvres", "Mozart", "Mail"],
  },
  {
    name: "Étampes",
    slug: "etampes",
    dept: "91",
    population: 25_000,
    description: "Étampes : enlèvement épave sous 24–48h, rachat possible selon état.",
    neighborhoods: ["Centre", "Saint-Michel", "Guinette", "Saint-Pierre", "Vallée"],
  },
  {
    name: "Les Ulis",
    slug: "les-ulis",
    dept: "91",
    population: 25_000,
    description: "Les Ulis : intervention épaviste locale avec process administratif complet.",
    neighborhoods: ["Centre", "Aulnes", "Bosquets", "Amonts", "Courdimanche"],
  },
  {
    name: "Viry-Châtillon",
    slug: "viry-chatillon",
    dept: "91",
    population: 31_000,
    description: "Viry-Châtillon : retrait VHU rapide en zone résidentielle et axes denses.",
    neighborhoods: ["Centre", "Plateau", "Port Aviation", "Lac", "Mairie"],
  },
  {
    name: "Courbevoie",
    slug: "courbevoie",
    dept: "92",
    population: 84_000,
    description: "Courbevoie : enlèvement d'épave rapide, y compris secteur La Défense.",
    neighborhoods: ["Bécon", "Faubourg de l'Arche", "Centre", "Gare", "Charras"],
  },
  {
    name: "Suresnes",
    slug: "suresnes",
    dept: "92",
    population: 49_000,
    description: "Suresnes : service épaviste agréé avec devis immédiat et prise en charge rapide.",
    neighborhoods: ["Centre", "Cité-Jardins", "Mont-Valérien", "Raguidelles", "Liberté"],
  },
  {
    name: "Antony",
    slug: "antony",
    dept: "92",
    population: 63_000,
    description: "Antony : enlèvement VHU et rachat épave avec intervention sous 24–48h.",
    neighborhoods: ["Centre", "Croix de Berny", "Noyer Doré", "Pajeaud", "Baconnets"],
  },
  {
    name: "Villepinte",
    slug: "villepinte",
    dept: "93",
    population: 39_000,
    description: "Villepinte : enlèvement d'épaves rapide avec adaptation aux zones logistiques.",
    neighborhoods: ["Centre", "Parc de la Noue", "Vert-Galant", "Europe", "Mairie"],
  },
  {
    name: "Bondy",
    slug: "bondy",
    dept: "93",
    population: 54_000,
    description: "Bondy : épaviste local, service rapide et documents conformes VHU.",
    neighborhoods: ["Centre", "Mairie", "Le Mainguy", "Remise à Jorelle", "La Mare à la Veuve"],
  },
  {
    name: "Bagnolet",
    slug: "bagnolet",
    dept: "93",
    population: 39_000,
    description: "Bagnolet : enlèvement épave en 24–48 h avec estimation gratuite.",
    neighborhoods: ["Centre", "La Dhuys", "Malassis", "Coutures", "Raspail"],
  },
  {
    name: "Charenton-le-Pont",
    slug: "charenton-le-pont",
    dept: "94",
    population: 31_000,
    description: "Charenton-le-Pont : service épaviste rapide aux portes de Paris.",
    neighborhoods: ["Centre", "Valmy", "Concorde", "Bercy", "Liberté"],
  },
  {
    name: "Joinville-le-Pont",
    slug: "joinville-le-pont",
    dept: "94",
    population: 20_000,
    description: "Joinville-le-Pont : enlèvement VHU et rachat selon état, 7j/7.",
    neighborhoods: ["Centre", "Polangis", "Palissy", "Bords de Marne", "Vautier"],
  },
  {
    name: "Choisy-le-Roi",
    slug: "choisy-le-roi",
    dept: "94",
    population: 46_000,
    description: "Choisy-le-Roi : enlèvement d'épaves rapide en habitat dense et zones mixtes.",
    neighborhoods: ["Centre", "Lugny", "Gondoles", "Parc", "Seine"],
  },
  {
    name: "Franconville",
    slug: "franconville",
    dept: "95",
    population: 37_000,
    description: "Franconville : service épaviste local, devis gratuit et intervention rapide.",
    neighborhoods: ["Centre", "Épine-Guyon", "Bel Air", "Moulin", "Gare"],
  },
  {
    name: "Bezons",
    slug: "bezons",
    dept: "95",
    population: 33_000,
    description: "Bezons : enlèvement épave en 24–48h avec accompagnement VHU complet.",
    neighborhoods: ["Centre", "Agriculture", "Chênes", "Bords de Seine", "Val Notre-Dame"],
  },
  {
    name: "Taverny",
    slug: "taverny",
    dept: "95",
    population: 27_000,
    description: "Taverny : enlèvement VHU rapide avec prise en charge réglementaire.",
    neighborhoods: ["Centre", "Vaucelles", "Verdun", "Sarcelles", "Bois de Boissy"],
  },
  {
    name: "Herblay-sur-Seine",
    slug: "herblay-sur-seine",
    dept: "95",
    population: 31_000,
    description: "Herblay-sur-Seine : service épaviste local et rachat selon valorisation.",
    neighborhoods: ["Centre", "Bords de Seine", "La Patte d'Oie", "Butte", "Edison"],
  },
];

export const SERVICE_PAGES = [
  {
    href: "/enlevement-epave-gratuit",
    label: "Enlèvement épave gratuit",
  },
  { href: "/rachat-epave", label: "Rachat épave" },
  { href: "/epaviste-agree", label: "Épaviste agréé" },
  { href: "/vehicule-hors-usage", label: "Véhicule hors d’usage" },
  { href: "/certificat-destruction", label: "Certificat de destruction" },
] as const;

export const DEPT_ROUTE_BY_SLUG: Record<string, string> = {
  "paris-75": "/epaviste-paris-75",
  "seine-et-marne-77": "/epaviste-seine-et-marne-77",
  "yvelines-78": "/epaviste-yvelines-78",
  "essonne-91": "/epaviste-essonne-91",
  "hauts-de-seine-92": "/epaviste-hauts-de-seine-92",
  "seine-saint-denis-93": "/epaviste-seine-saint-denis-93",
  "val-de-marne-94": "/epaviste-val-de-marne-94",
  "val-d-oise-95": "/epaviste-val-d-oise-95",
};

export const CITY_ROUTES = [
  "/epaviste-paris",
  "/epaviste-boulogne-billancourt",
  "/epaviste-saint-denis",
  "/epaviste-argenteuil",
  "/epaviste-montreuil",
  "/epaviste-versailles",
  "/epaviste-nanterre",
  "/epaviste-vitry-sur-seine",
  "/epaviste-creteil",
  "/epaviste-asnieres-sur-seine",
  "/epaviste-chelles",
  "/epaviste-melun",
  "/epaviste-meaux",
  "/epaviste-mantes-la-jolie",
  "/epaviste-saint-germain-en-laye",
  "/epaviste-poissy",
  "/epaviste-corbeil-essonnes",
  "/epaviste-evry-courcouronnes",
  "/epaviste-palaiseau",
  "/epaviste-levallois-perret",
  "/epaviste-neuilly-sur-seine",
  "/epaviste-colombes",
  "/epaviste-aubervilliers",
  "/epaviste-pantin",
  "/epaviste-aulnay-sous-bois",
  "/epaviste-ivry-sur-seine",
  "/epaviste-villejuif",
  "/epaviste-champigny-sur-marne",
  "/epaviste-cergy",
  "/epaviste-sarcelles",
  "/epaviste-torcy",
  "/epaviste-noisiel",
  "/epaviste-lagny-sur-marne",
  "/epaviste-pontault-combault",
  "/epaviste-sartrouville",
  "/epaviste-conflans-sainte-honorine",
  "/epaviste-les-mureaux",
  "/epaviste-trappes",
  "/epaviste-massy",
  "/epaviste-longjumeau",
  "/epaviste-juvisy-sur-orge",
  "/epaviste-ris-orangis",
  "/epaviste-issy-les-moulineaux",
  "/epaviste-clichy",
  "/epaviste-puteaux",
  "/epaviste-rueil-malmaison",
  "/epaviste-bobigny",
  "/epaviste-drancy",
  "/epaviste-rosny-sous-bois",
  "/epaviste-noisy-le-sec",
  "/epaviste-maisons-alfort",
  "/epaviste-alfortville",
  "/epaviste-vincennes",
  "/epaviste-nogent-sur-marne",
  "/epaviste-ermont",
  "/epaviste-gonesse",
  "/epaviste-pontoise",
  "/epaviste-garges-les-gonesse",
  "/epaviste-fontainebleau",
  "/epaviste-provins",
  "/epaviste-dammarie-les-lys",
  "/epaviste-bussy-saint-georges",
  "/epaviste-guyancourt",
  "/epaviste-velizy-villacoublay",
  "/epaviste-etampes",
  "/epaviste-les-ulis",
  "/epaviste-viry-chatillon",
  "/epaviste-courbevoie",
  "/epaviste-suresnes",
  "/epaviste-antony",
  "/epaviste-villepinte",
  "/epaviste-bondy",
  "/epaviste-bagnolet",
  "/epaviste-charenton-le-pont",
  "/epaviste-joinville-le-pont",
  "/epaviste-choisy-le-roi",
  "/epaviste-franconville",
  "/epaviste-bezons",
  "/epaviste-taverny",
  "/epaviste-herblay-sur-seine",
] as const;
